
<h2>Show Meetup id : <?= $meetup->getId()?> </h2>



    <div class="row">

        <div class="col-sm-3">
            <h4>Title :</h4>
            <?= $meetup->getTitle()?>
        </div>
        <div class="col-sm-3">
            <h4>Description :</h4>
            <?= $meetup->getDescription()?>
        </div>


  
        <div class="col-sm-2">
            <h4>Date de début :</h4>
            <?= $meetup->getDateStart()->format('Y-m-d')?>
        </div>

        <div class="col-sm-2">
            <h4>Date de fin :</h4>
            <?= $meetup->getDateEnd()->format('Y-m-d')?>
        </div>

        <div class="col-sm-2">
            <h4>Organisateur:</h4>
            <?= $meetup->getOrganisateur()?>
        </div>

    </div>
    <div class="row">
        <a class="btn btn-primary" href="<?= $this->url('meetups') ?>"> Back to List</a>
    </div>

